export type Theme = 'Safety' | 'Livability' | 'Future'

export const samplePrompts: Record<Theme, string[]> = {
  Safety: [
    'An Emirati mother in a flowing black abaya and black shayla hijab, warm olive complexion and gentle dark eyes, holds her toddler dressed in a crisp little white thobe on the Abu Dhabi Corniche promenade at sunset. Tall date palm trees line the marble walkway behind them and the city skyline glows amber gold across the Arabian Gulf. Medium close-up shot, soft golden hour lighting, warm amber and rose tones, tender and protective mood. Photorealistic cinematic style.',
    'A young Emirati man in an ankle-length pristine white kandura, white ghutra secured with a black agal rope, well-groomed dark beard and warm tan complexion, stands in a landscaped Abu Dhabi public park during the evening, speaking with quiet confidence. Softly lit pathways, native desert shrubs, and gently swaying date palms surround him. Chest-up portrait framing, soft evening twilight with warm streetlight ambiance, calm and reflective mood. Photorealistic cinematic style.',
    'A grand boulevard in Abu Dhabi at night, lined with tall date palms wrapped in golden light and elaborate Arabic calligraphy light installations draped across lampposts and pedestrian bridges. White Toyota Land Cruisers and sleek modern cars glide along the wide asphalt boulevard, their polished surfaces reflecting vibrant amber neon. Wide establishing shot from street level, rich warm yellow and gold tones, festive and celebratory mood. Photorealistic cinematic style.',
    'A group of Emirati men in white kandura and ghutra with black agal, alongside women in flowing black abayas and children in traditional dress, cross a wide illuminated pedestrian crossing near the Emirates Palace on a warm Abu Dhabi evening. Arabic signage glows on modern storefronts and tall date palms frame the grand boulevard. Wide street-level shot, warm golden artificial lighting, safe and vibrant atmosphere, authentic Emirati community mood. Photorealistic cinematic style.',
  ],

  Livability: [
    'An Emirati family strolls along the Abu Dhabi Corniche promenade during golden hour — the father in a crisp white kandura and ghutra with black agal, the mother in a flowing black abaya and shayla hijab, their children running ahead laughing with joy. Tall date palms cast long shadows across the marble walkway and the azure Arabian Gulf stretches to the horizon beneath a warm amber sky. Wide cinematic shot, warm golden hour sunlight casting long soft shadows, peaceful and luxurious mood, rich amber and gold tones. Photorealistic cinematic style.',
    'Young Emirati professionals in pristine white kandura and elegant black abayas ride electric scooters and walk together through the clean shaded streets of Masdar City on a bright sunny day. Children with warm olive skin and dark eyes play freely around the innovative sustainable architecture. Date palms and native desert plants line the wide pedestrian pathways. Dynamic tracking shot at street level, bright midday sun with deep blue sky, energetic and forward-thinking mood. Photorealistic cinematic style.',
    'An Emirati couple — the man in a relaxed white kandura, the woman in a flowing black abaya — recline comfortably on sunbeds beside a pristine infinity pool at a luxury beach resort on Saadiyat Island, overlooking the crystal-clear Arabian Gulf. Date palms sway gently nearby and the Abu Dhabi skyline shimmers faintly in the warm afternoon haze across the water. Wide shot with shallow depth of field, soft warm afternoon sunlight, calm and sophisticated mood, ivory and azure tones. Photorealistic cinematic style.',
  ],

  Future: [
    'An Emirati man in a white kandura and ghutra with black agal walks confidently along a clean car-free boulevard in a futuristic Abu Dhabi district where solar panels are woven elegantly into the facades of soaring sandstone-and-glass skyscrapers. Lush vertical gardens cascade down building walls and autonomous electric pods glide silently on magnetic tracks beside him. Arabic holographic signage floats above the street. Slow tracking shot at eye level, golden hour light transitioning to cool blue dusk, serene and optimistic mood. Photorealistic cinematic style.',
    'A young Emirati woman in a flowing floor-length black abaya and black shayla hijab, warm olive complexion and focused dark eyes, interacts with a holographic smart city interface displaying Arabic and English data at the Al Maryah Island financial district. Futuristic digital displays and autonomous vehicles move seamlessly behind her in the ultra-modern glass-and-steel streetscape. Close-up tracking shot at eye level, dramatic dusk lighting with amber and rose sky transitioning to cool blue city lights, innovative and confident mood. Photorealistic cinematic style.',
    'Emirati men in white kandura and ghutra with black agal walk purposefully through a bustling high-tech transit plaza in Abu Dhabi, where the marble-and-glass plaza surface has integrated glowing LED pathways pulsing with data beneath their feet. Tall date palms line the perimeter and translucent glass towers display holographic energy maps in Arabic script. Wide establishing shot with slow camera push forward, cool blue and silver ambient lighting with warm accent tones, intelligent and connected mood. Photorealistic cinematic style.',
    'A young Emirati woman in a white lab coat worn over her flowing black abaya carefully tends to rows of genetically optimized plants inside a vast climate-controlled vertical farm bathed in soft magenta grow lights. Her warm olive complexion and focused dark eyes reflect the glow of surrounding screens showing real-time crop and water data in Arabic script. Alternating close-up and medium shots, soft magenta and violet grow light ambiance, precise and quietly revolutionary mood. Photorealistic cinematic style.',
  ],
}

export function getSamplePromptsForTheme(theme: Theme): string[] {
  return samplePrompts[theme] ?? []
}
