export type Theme = 'Safety' | 'Livability' | 'Future'

export const samplePrompts: Record<Theme, string[]> = {
  Safety: [
    'A medium close-up shot of a smiling Middle Eastern woman wearing a beige hijab and a brown leather jacket, holding a toddler in a white winter hat. They are standing on an urban coastal boardwalk during sunset. In the background, a modern city skyline with tall skyscrapers is softly blurred by a shallow depth of field and a warm golden haze. Cinematic, photorealistic, 4k, natural daylight, shot on 35mm lens.',
    'A chest-up portrait shot of a young Emirati man wearing a crisp white traditional Kandura and Ghutra. He is speaking candidly, looking slightly off-camera. The lighting is soft evening twilight. The background shows a dimly lit urban park with warm, out-of-focus streetlights. High detail, realistic skin texture, documentary style, cinematic.',
    'A tracking shot from a moving vehicle looking out at a wide city avenue at night in Abu Dhabi. The street is beautifully decorated with glowing, elaborate light installations shaped like Arabic calligraphy and festive symbols draped across lampposts and bridges. Modern cars are driving on the asphalt, reflecting the vibrant yellow and green neon lights. High-end cinematography, night photography, crisp details, 4k.',
    'A slow-motion street-level shot of a group of diverse pedestrians crossing a well-lit city street at a crosswalk at night. In the background, modern buildings are illuminated, and a white SUV sits at the traffic light. The atmosphere is safe and vibrant. Cinematic city lighting, rich contrast, realistic movement.',
  ],

  Livability: [
    'A wide, cinematic shot of the Abu Dhabi Corniche during the golden hour. In the foreground, a vibrant, modern family walking along the paved promenade, laughing and enjoying the cool sea breeze. In the background, the iconic Abu Dhabi skyline featuring architectural masterpieces and glass skyscrapers glittering under the warm, orange sun. The atmosphere is peaceful, luxurious, and family-friendly. High-resolution, 4k, realistic texture, soft natural lighting, smooth camera pan from left to right',
    'A vibrant, sunny day in Masdar City. A diverse group of friends and children are playing and riding electric scooters on a clean, futuristic, and sustainable street lined with lush green trees and innovative architecture. The scene captures the blend of technology and nature. Focus on a happy child smiling as they zoom past on a scooter. Warm, bright daylight, high contrast, crisp details, professional cinematography, handheld camera style to give an energetic and authentic feeling.',
    'A beautiful, bright day at a high-end Abu Dhabi beach resort. A stylish, relaxed couple is lounging on comfortable sunbeds by a pristine, infinity-style swimming pool that overlooks the clear blue Arabian Gulf. In the distance, the faint, shimmering silhouette of the city skyline. Gentle waves are splashing softly in the background. The mood is calm, sophisticated, and rejuvenating. Soft, cinematic color grading, shallow depth of field focusing on the couple, peaceful atmosphere, 8k resolution.',
  ],

  Future: [
    'A wide-angle, cinematic drone shot of a futuristic city integrated with nature. Solar panels are elegantly woven into the architectural design of skyscrapers, shimmering with a soft blue hue under the golden hour light. Below, lush vertical gardens cover building facades, while autonomous electric pods glide silently on magnetic tracks along clean, car-free streets. The atmosphere is serene and optimistic. High-resolution, 4K, hyper-realistic, soft natural lighting, smooth steady forward flight movement.',
    'Close-up tracking shot at eye level of a young Emirati woman in a sleek black abaya and hijab interacting with a holographic smart city interface at the Al Maryah Island financial district. Futuristic digital displays and autonomous vehicles move seamlessly behind her in the ultra-modern streetscape. Dramatic dusk lighting with amber and rose sky transitions into cool blue city lights. Rich cool blue and silver tones with warm accent lighting, innovative and forward-thinking mood. Portrait orientation, subjects fully upright, vertical 9:16 frame. Photorealistic, cinematic quality, ultra-detailed, 15-second video clip.',
    'A low-angle tracking shot capturing a sleek, white autonomous car maneuvering through a bustling, high-tech transit plaza. The street surface has integrated glowing LED pathways that pulse with data, symbolizing a blockchain-secured smart traffic grid. In the background, tall, translucent glass structures display holographic maps of the city energy consumption. People are moving calmly, engaged with AR glasses. Cinematic lighting with deep shadows and vibrant light accents, 8K, realistic textures, professional film aesthetic, steady camera tracking at eye-level',
    'A macro close-up shot focusing on a robotic arm delicately tending to genetically optimized plants inside a climate-controlled vertical farm. The room is filled with soft, magenta-tinted grow lights. In the background, out-of-focus digital screens show real-time blockchain data tracking crop growth and distribution. The camera slowly pans and zooms in on the robotic limb, showing intricate mechanical movements and fine details. Moody, high-contrast lighting, cinematic depth of field, 4K resolution, clean and futuristic industrial style.'
  ],
}

export function getSamplePromptsForTheme(theme: Theme): string[] {
  return samplePrompts[theme] ?? []
}
