export type Theme = 'Safety' | 'Livability' | 'Future'

export const samplePrompts: Record<Theme, string[]> = {
  Safety: [
    'An Emirati mother in a flowing black abaya and black shayla hijab, warm olive complexion and gentle dark eyes, holds her toddler dressed in a crisp little white thobe on the Abu Dhabi Corniche promenade at sunset. Tall date palm trees line the marble walkway behind them and the city skyline glows amber gold across the Arabian Gulf. Medium close-up shot, soft golden hour lighting, warm amber and rose tones, tender and protective mood. Photorealistic cinematic style.',
    'A young Emirati man in an ankle-length pristine white kandura, white ghutra secured with a black agal rope, well-groomed dark beard and warm tan complexion, stands in a landscaped Abu Dhabi public park during the evening, speaking with quiet confidence. Softly lit pathways, native desert shrubs, and gently swaying date palms surround him. Chest-up portrait framing, soft evening twilight with warm streetlight ambiance, calm and reflective mood. Photorealistic cinematic style.',
    'A grand boulevard in Abu Dhabi at night, lined with tall date palms wrapped in golden light and elaborate Arabic calligraphy light installations draped across lampposts and pedestrian bridges. White Toyota Land Cruisers and sleek modern cars glide along the wide asphalt boulevard, their polished surfaces reflecting vibrant amber neon. Wide establishing shot from street level, rich warm yellow and gold tones, festive and celebratory mood. Photorealistic cinematic style.',
    'A group of Emirati men in white kandura and ghutra with black agal, alongside women in flowing black abayas and children in traditional dress, cross a wide illuminated pedestrian crossing near the Emirates Palace on a warm Abu Dhabi evening. Arabic signage glows on modern storefronts and tall date palms frame the grand boulevard. Wide street-level shot, warm golden artificial lighting, safe and vibrant atmosphere, authentic Emirati community mood. Photorealistic cinematic style.',
  ],

  Livability: [
    'An Emirati family strolls along the Abu Dhabi Corniche promenade during golden hour — the father in a crisp white kandura and ghutra with black agal, the mother in a flowing black abaya and shayla hijab, their children running ahead laughing with joy. Tall date palms cast long shadows across the marble walkway and the azure Arabian Gulf stretches to the horizon beneath a warm amber sky. Wide cinematic shot, warm golden hour sunlight casting long soft shadows, peaceful and luxurious mood, rich amber and gold tones. Photorealistic cinematic style.',
    'Young Emirati professionals in pristine white kandura and elegant black abayas ride electric scooters and walk together through the clean shaded streets of Masdar City on a bright sunny day. Children with warm olive skin and dark eyes play freely around the innovative sustainable architecture. Date palms and native desert plants line the wide pedestrian pathways. Dynamic tracking shot at street level, bright midday sun with deep blue sky, energetic and forward-thinking mood. Photorealistic cinematic style.',
    'An Emirati couple — the man in a relaxed white kandura, the woman in a flowing black abaya — recline comfortably on sunbeds beside a pristine infinity pool at a luxury beach resort on Saadiyat Island, overlooking the crystal-clear Arabian Gulf. Date palms sway gently nearby and the Abu Dhabi skyline shimmers faintly in the warm afternoon haze across the water. Wide shot with shallow depth of field, soft warm afternoon sunlight, calm and sophisticated mood, ivory and azure tones. Photorealistic cinematic style.',
  ],

  Future: [
    'An Emirati man in a white kandura and ghutra with black agal walks confidently along a clean tree-lined boulevard in the Masdar City eco-district of Abu Dhabi, where modern buildings are fitted with solar panels glinting under the golden afternoon sun. Electric vehicles charge silently at smart charging stations and lush native plants and tall date palms line the wide pedestrian walkways. Other Emirati professionals in traditional dress walk alongside him. Slow tracking shot at eye level, warm golden afternoon sunlight, optimistic and forward-thinking mood. Photorealistic cinematic style.',
    'A young Emirati woman in a flowing floor-length black abaya and black shayla hijab, warm olive complexion and focused dark eyes, stands at a sleek smart city digital kiosk on the Al Maryah Island waterfront, navigating a touchscreen interface displaying real-time city services and data in Arabic and English. Modern glass towers reflect the late afternoon sky behind her and well-dressed professionals pass by on the marble promenade. Close-up tracking shot at eye level, bright warm afternoon sunlight, confident and progressive mood. Photorealistic cinematic style.',
    'Emirati men in white kandura and ghutra with black agal and Emirati women in elegant black abayas board a sleek modern electric shuttle at a spotless state-of-the-art transit station in Abu Dhabi. The station features clean white architecture, digital departure boards in Arabic and English, and tall date palms lining the entrance plaza. Wide establishing shot with slow camera push forward, bright midday sun with deep blue sky, efficient and progressive mood. Photorealistic cinematic style.',
    'A young Emirati woman in a white lab coat worn over her flowing black abaya carefully tends to rows of lush green plants inside a modern climate-controlled vertical farm in Abu Dhabi, lit by clean white and soft green LED grow lights. Her warm olive complexion and focused dark eyes reflect the glow of the thriving plants surrounding her. Digital monitoring screens on the walls display crop and water data in Arabic and English. Alternating close-up and medium shots, soft green and white LED lighting, precise and sustainable mood. Photorealistic cinematic style.',
  ],
}

export function getSamplePromptsForTheme(theme: Theme): string[] {
  return samplePrompts[theme] ?? []
}
